defaults:
  - _self_
  - algo: trpo
  - r_model: all_constraints
  - restrict_days: qhi
  - forecasts: num_elig
  - shaped_penalty: none
 
datadir: data/processed
county: 36005 # bronx # 4013 = maricopa
seed: 12345
num_posterior_samples: 100
model_name: test

train_years: [2006, 2008, 2009, 2010, 2012, 2013, 2014, 2016]
val_years: [2007, 2011, 2015]

num_envs: 32 
parallel: false
training_timesteps: 15_000_000 
match_similar: true
sample_budget: true
explore_budget: false
penalty: 0.0 

eval_mode: false
eval:
  penalty: 0.0 # never penalize during evaluation
  freq: 2500
  episodes: 100
  eval_mode: false
  val_years: true
  match_similar: true

policy_type: RL
final_eval_episodes: 1000
