defaults:
  - _self_
  - algo: ppo

datadir: data/processed
county: 36005 # bronx
# county: 4013 # maricopa
seed: 12345
num_posterior_samples: 100
guide_ckpt: ckpts/FullFast_8-16_guide.pt # ckpts/Full_8-16_guide.pt
model:  # must match exactly the model used when producing the guide
        # in the future linking them will be automatic
  num_hidden_layers: 1
  hidden_dim: 32
model_name: test

train_years: [2006, 2008, 2009, 2010, 2012, 2013, 2014, 2016]
val_years: [2007, 2011, 2015]

num_envs: 32 # 1
parallel: false
training_timesteps: 10_000_000 # 3_000_000
match_similar: true
sample_budget: true
penalty: 0.2 # 1.0
penalty_decay: true
eval_mode: false

eval:
  penalty: 0.0 # no penalty during evaluation
  freq: 1000
  episodes: 25
  eval_mode: false
  val_years: true
  match_similar: true

policy_type: RL
final_eval_episodes: 1000
