name: heatrl
channels:
 - defaults
 - conda-forge
 - pytorch
dependencies:
  - python=3.10
  - xarray=2022.11.0
  - netcdf4=1.6.2
  - gdal=3.0.2
  - rasterio=1.2.10
  - rasterstats=0.19.0
  - pip=23.1.2 
  - pytorch:pytorch=2.0.1
  - cmdstanpy=1.1.0
  - ipykernel=6.20.2
  - pip:
    - geopandas==0.13.2
    - hydra-core==1.3.0
    - pytorch-lightning==2.0.4
