_target_: sb3_contrib.QRDQN
policy: MlpPolicy
policy_kwargs:
  net_arch: [16, 16]
  n_quantiles: 20 # 10 # 50
exploration_fraction: 0.25
exploration_final_eps: 0.1
batch_size: 512
learning_rate: 0.001
gamma: 1.0
