model:
  num_hidden_layers: 1
  hidden_dim: 32
  name: FF_8-16
training:
  batch_size: null
  epochs: 80
  gradient_clip_val: 1.0
  lr: 0.001
  num_workers: 0
  num_particles: 1
  max_steps: -1
  jit: true
datadir: bayesian_model/data/processed
