defaults:
  - _self_
  - model: nn
  - training: fast

model:
  num_hidden_layers: ???
  hidden_dim: ???
  name: ???

training:
  batch_size:   # leave empty it will be chose according to S and N
  epochs: ???
  gradient_clip_val: 1.0
  lr: 0.001
  num_workers: 8
  num_particles: 10
  max_steps: -1  # no max steps
  jit: true

datadir: data/processed
